### PR TITLE
Login required refactor

### PR DESCRIPTION
**Pull request by enoren5**
Here is my progress and change log so far today.  I:
-  deleted the obsolete custom middleware 
-  commented out the custom middleware references in `settings.py`
- leveraged `@login_required` decorators and `LoginRequiredMixin`'s throughout the entire codebase against all `views.py`'s
- leveraged CBVs to write 2 new views to generate and automate top-level landing page which handles user login credentials - - no need to do this manually in a view
- re-wrote `accounts/urls.py`
- purged all legacy code buried in comments. All clean now

Two outstanding issues which require attention and development beyond my capabilities:
- In my adventures refactoring my code base as described above, according to this traceback below, I introduced a bug. The 'next' and 'previous' button links  in the `generators` web app are now broken. Django seems to point towards a `User`/`user` configuration issue, although I can't tell for certain. When navigating to a valid url (such as: `http://127.0.0.1:8000/tarot_key/21` which worked before my changes), Django is now throwing  a 500 with this traceback:
  ```
  AttributeError at /tarot_key/21
  'list' object has no attribute 'user'
  ```
  And then highlights and points to this line in my `generators/views.py`:
  ```
  prev_generator, next_generator = getPrevNext(generator_array, generator_number) 
  ```
- The `is_protected` BooleanField inside accounts app `models.py` needs to switch / toggle `@login_required` and `LoginRequiredMixin` restrictions on / off. For example, when turned 'on', when a web visitor lands on the top level page, to descend down into the rest of the website, they need to enter valid credentials. That works great already. But what needs to be completed next is that when the Admin Dashboard staff user toggles the switch 'off', the top-level page (gateway) is gone and any web visitor can descend and navigate around the site ('portal' page and everywhere else) without credentials or restrictions. I experimented and [asked about how to implement a feature like this elsewhere on the web here some time ago](https://forum.djangoproject.com/t/switch-to-toggle-loginrequiredmixin-on-off/16493/). That forum thread is long and verbose. It's mostly excessive rambling and not important. You don't need to read all of it. The "general architecture" (the take away relevant part to implementing the task at hand) as described by a senior member explains how to build the feature in this way:
    - Create a model to contain the indicator of whether logins are required or not.
    - Create your admin page to allow for that indicator to be changed
    - Create the subclass for LoginRequiredMixin (Start by reviewing the source for it in django.contrib.auth.mixins - the mixin is only about 7 lines long.)
    - Change the dispatch method to have the check for is_authenticated to only be performed if your indicator defined above is set to do so
    - Alternative to the above - don’t subclass it, since this mixin only contains one function, and you’re replacing it. Just create a new class inheriting from AccessMixin with your new dispatch method.
    - Change all your views to use your new mixin
  
I'm not sure how to do that. This is Abu's role

### CODE REVIEW

**Comment by abubakarA-Dot** [comment]
Hi @enoren5 
I have added new functionality in my recent push in which I am over riding the dispatch method to add extra functionality in LoginVew class which is to log the user out automatically after a time session ends.

**Comment by enoren5** [comment]
The `is_protected` toggle originally required a 60 second timer. Thank you for doing that. However this is really secondary and less important. Rather, the `is_protected` feature needs to turn the gateway template and username-password combo requirement on/off. I thought I explained that thoroughly above. You seemed to have missed this.

The current problem appears at 24 seconds into the video below. At that mark, the staff Admin switches the `is_protected` tick box off and clicks Save. But when the Admin signs out and goes back to `localhost:9001`, the gateway is still in the way. Instead Django should be routing to portal without the gateway template being served at all. This main component still needs to be built. @abubakarA-Dot : Please complete this feature.

[Screencast from 2023-04-19 18-19-12.webm](https://user-images.githubusercontent.com/6686723/233213115-25ace64e-7426-4a3e-b1dd-d13a28fcd5d1.webm)

**Comment by abubakarA-Dot** [comment]
Hi @enoren5 
I have fixed the issues related to login redirection when an admin logs out from the admin panel. Before fixing this issue, it was redirecting a user to the login page again when is_protected turns False, it should serve the portal endpoint/page instead and it is behaving this way now. I also wanted to discuss the home page endpoint for non-admin users. When a session starts for a user( non admin ), then the user should not get logged out until the session ends itself ( when there were custom middlewares, it was logging the user out upon clicking on the home endpoint/button. The user can get logged out using the logout button from the portal page to end the current session.
Please test the new changes and let me know if something needs to be added or fixed from this PR. thanks

**Comment by enoren5** [comment]
I've tested. The custom `accounts/custom_decorator.py` script is well written and accomplishes the main objective. Excellent job! Thank you Abu. I am really pleased with this progress.

There is just a little more work to do I belive before I can mark this milestone as complete. 

In the `generators` web app, instead of a `@login_required` decorator the project uses a CBV which means a `LoginRequiredMixin` protects and handles session behavior. So this `LoginRequiredMixin` needs to be customized to perform the same task as what you already did in `accounts/custom_decorator.py`.  One obstacle to testing this is that it is currently broken with Django serving a 404 or 500 even when an url route is accurate and data in the db exists. So this bug might need to be fixed before you can test and continue to implement the custom `LoginRequiredMixin` feature. This same issue I described above in greater detail in my original comment as the first bullet point under: "Two outstanding issues which require attention and development beyond my capabilities". Once this bug is resolved, then you can complete the task by writing a custom Mixin. 

Thanks Abu

**Comment by abubakarA-Dot** [comment]
@enoren5 ,
The issue related to the random key generator has been fixed. now there is no error that was mentioned in your outstanding errors ```
AttributeError at /tarot_key/21
'list' object has no attribute 'user'
```
What I did here is that removed the LoginRequiredMixin as I was handling the login required logic in custom decorator. I also removed the decorator implementation from RandomGenerator class's get() function and it worked.
I was also caling the decorator on 
```
def getPrevNext(array, element):
    result = array.index(element)
    return  [array[result - 1], array[(result + 1) % len(array)]]
```
which was not required as I was calling the decorator on tarot_key function already.
I hope it will fix the issue related to 500 and 404 errors as well. Please let me know if any thing else needs to be fixed.

**Comment by enoren5** [comment]
Hi Abu! Thank you for fixing the `generators` web app. I tested with db.sqlite3 and with the temote testing PostgreSQL instance exported locally. They both work. 

However I continued testing and noticed that the `landings` web app (screenshot below) shows an Operations error when trying to view or save content. This needs to be resolved for both:
1. db.sqlite3
2. PostgreSQL testing instance

For the second one, I will send you a direct message on UpWork with the `export` command because it includes the db username and password that I don't want to share publicly on GitHub.

landings app error

**Pull request merged**
